### ISSUE TITLE
It doesn't work in the Hypershade's NodeEditor. At least not by default.

### ISSUE THREAD

**Issue by UberBringer** [illmillrig/NodeAlignDeez#3]
I like what the script is doing but I'm only using the NodeEditor within the Hypershade.
It's quite easy to make that work.

look for the "_findPanelEditor()" function and change "nodeEditorPanel1" to "hyperShadePrimaryNodeEditor"

Maybe this could be changed to use the focused window in future.

Is it possible to dock the AlignDeez window ?
I tried this:
`dockControl -area right -content AlignDeez AlignDeezDocked;`
But maya is giving me this:
`// Error: line 1: Object 'AlignDeez' not found. //`

Is that the wrong window Name?

**Comment by illmillrig** [comment]
You have to wrap the Maya window with shiboken to access the align deez UI. 

None of this is in mel. Sorry.
