### ISSUE TITLE
Download and usage question 

### ISSUE THREAD

**Issue by SheepDomination** [illmillrig/NodeAlignDeez#5]
Where is the link to download; as it looks promising ?

What do you mean, 

> **Currently only supports the first tab in a node editor ?

**Comment by artintime** [comment]
Just like script editor you can have many tabs or windows (in node editor) i guess there must be some different underline codes to switch to other tabs that this scrpt can't communicate.
Was also wondering where was the script itself, guess he found a flow and fixing it to repost but at least i'd put a note up.
