### ISSUE TITLE
is the file still downloadable? the folder contains only a "read me"

### ISSUE THREAD

**Issue by AlexxB31** [illmillrig/NodeAlignDeez#6]

**Comment by melMass** [comment]
Same question

**Comment by illmillrig** [comment]
This was really just a tool to show that the node editor experience can be vastly improved.  Even much  more beyond what i've done here.  Just about every other DCC's 'node' editor is superior to Maya's, and Autodesk acts like this is fine, and there's nothing that needs to change. Please put in a ticket with Autodesk to improve the node editor in maya.
